version: '3.7'

services:
  pin-bot:
    build: .
    restart: always
    environment:
      NODE_ENV: production
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
